version: '3.8'

services:
  ml-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=true
    restart: unless-stopped
